#!/usr/bin/env bash

TEMP_DIR=$(mktemp -d)

echo "[+] Download Marksman 2022-12-28"
echo "[-] Binary will be downloaded into ${TEMP_DIR}"

curl -L https://github.com/artempyanykh/marksman/releases/download/2022-12-28/marksman-linux -o "${TEMP_DIR}/marksman"

echo "[+] Move Downloaded file into ${HOME}/.local/bin"
mv "${TEMP_DIR}/marksman" "${HOME}/.local/bin/marksman"

echo "[+] Make Execuatable"
chmod +x "${HOME}/.local/bin/marksman"
