#!/usr/bin/env bash

echo "[+] Install NetworkManager"
sudo pacman -S --noconfirm networkmanager

echo "[+] Install Sof Firmware"
sudo pacman -S --noconfirm sof-firmware

echo "[+] Install Reqired Fonts"
sudo pacman -S --noconfirm otf-font-awesome terminus-font noto-fonts-cjk ttf-dejavu

echo "[+] Install i3Blocks & i3WM"
sudo pacman -S --noconfirm i3blocks i3-wm

echo "[+] Install Utilties"
sudo pacman -S --noconfirm wofi firefox helix git mako xdg-desktop-portal-wlr
