#!/usr/bin/env bash

TEMP_DIR=$(mktemp -d)

echo "[+] Check and Install Required Packages"
sudo pacman -S --needed git base-devel

echo "[+] Clone 'yay-bin' Repository"
git clone https://aur.archlinux.org/yay-bin.git "${TEMP_DIR}"

echo "[+] Install 'yay-bin'"
cd "${TEMP_DIR}" && makepkg -si